export { AutocompleteDecorationManager } from "./AutocompleteDecorationManager"
export { NextEditSuggestionProvider } from "./NextEditSuggestionProvider"
export { noopNextEditSuggestionAdapter } from "./NextEditSuggestionAdapter"
export { getInlineV2AutocompleteSettings, normalizeInlineV2AutocompleteSettings } from "./settings"
export type { NextEditSuggestionAdapter } from "./NextEditSuggestionAdapter"
export type { ReplaceCompletion, InlineV2AutocompleteSettings } from "./types"
