export { AutocompleteDecorationManager } from "./AutocompleteDecorationManager"
export { NextEditSuggestionProvider } from "./NextEditSuggestionProvider"
export { noopNextEditSuggestionAdapter } from "./NextEditSuggestionAdapter"
export { getSourceCraftAutocompleteSettings, normalizeSourceCraftAutocompleteSettings } from "./settings"
export type { NextEditSuggestionAdapter } from "./NextEditSuggestionAdapter"
export type { ReplaceCompletion, SourceCraftAutocompleteSettings } from "./types"
